---
# Backup system configuration file
#
# Postgres configuration
postgres:
  enabled: true
  actions:
    backup: true
    restore: false

  # Fake data
  backup:
    dir: /var/lib/postgresql/backup
    user: postgres
    password: postgres
    host: []
    port: 5432
    db: []
    db_prefix: []
    all_dbs: false
    compression: false
  restore:
    dir: /var/lib/postgresql/backup
    user: postgres
    password: postgres
    host:
      - localhost
      - example.com
    port: 5432
    db: []
    compression: false
